insert into Users (id, user_email, user_password, role)values(100, 'ana@email.com','$2a$12$A38mKnfWocV7uK9zc/KxOuei53EQkKXn/3Y1747KWuQDSmbJKLcnW','ROLE_ADMIN');
insert into Users (id, user_email, user_password, role)values(101, 'caua@email.com','$2a$12$DnRGdhJRYfinn5DdgkXbiOZhEdKL.q.nLq0LXciB4yvfVlYAlOSH2','ROLE_CLIENT');
insert into Users (id, user_email, user_password, role)values(123, 'sam@email.com','$2a$12$AJmWeuEWvCV1VtRNcS776OclrYrmcoEWw8YTrQVfCo1vC9ak6JVoa','ROLE_CLIENT');
insert into Users (id, user_email, user_password, role)values(102, 'toby@email.com','$2a$12$A38mKnfWocV7uK9zc/KxOuei53EQkKXn/3Y1747KWuQDSmbJKLcnW','ROLE_CLIENT');

insert into Clients (id,name,cpf,id_User,Phone_Number)values(10, 'Bianca Silva', '97688468019',101,'(11) 98765-4321');
insert into Clients (id,name,cpf,id_User,Phone_Number)values(20, 'Roberto Gomes', '81708991093',123,'21987654321');

insert into Movies (id, Name, Sinopse, Rating, Duration, Gender, Status)values(100, 'O Exterminador do Futuro 2: O Julgamento Final', 'Um ciborgue T-800 é enviado de volta no tempo para proteger um jovem John Connor de um novo e mais avançado ciborgue, o T-1000.', 'DEZESSEIS_ANOS', 8220000000000, 'ACAO', 'EM_CARTAZ');
insert into Movies (id, Name, Sinopse, Rating, Duration, Gender, Status)values(200, 'Senhor dos Anéis: A Sociedade do Anel', 'Um jovem hobbit, Frodo Bolseiro, herda um anel mágico e perigoso. Ele deve embarcar em uma jornada épica para destruí-lo antes que caia nas mãos de Sauron, o Senhor do Escuro.', 'DOZE_ANOS', 10680000000000, 'FANTASIA', 'EM_CARTAZ');
insert into Movies (id, Name, Sinopse, Rating, Duration, Gender, Status)values(300, 'A Teoria de Tudo', 'A história de Stephen Hawking e sua esposa Jane, que lutaram juntos contra a doença e os desafios da física, mudando a ciência para sempre.', 'LIVRE', 7380000000000, 'DRAMA', 'FORA_DE_CARTAZ');
insert into Movies (id, Name, Sinopse, Rating, Duration, Gender, Status)values(400, 'O Iluminado', 'Um escritor e ex-alcoólatra aceita um trabalho como zelador de inverno em um hotel isolado, onde seu filho começa a ter visões de fantasmas e o hotel o leva à loucura.', 'DEZESSEIS_ANOS', 8760000000000, 'TERROR', 'EM_CARTAZ');
insert into Movies (id, Name, Sinopse, Rating, Duration, Gender, Status)values(50, 'Toy Story', 'Um boneco de cowboy Woody se sente ameaçado e com ciúmes quando um novo e moderno boneco espacial, Buzz Lightyear, se torna o favorito de seu dono, Andy.', 'LIVRE', 4860000000000, 'ANIMACAO', 'EM_BREVE');
insert into Movies (id, Name, Sinopse, Rating, Duration, Gender, Status)values(60, 'Blade Runner 2049', 'Um novo blade runner, o Oficial K, descobre um segredo há muito enterrado que tem o potencial de mergulhar o que resta da sociedade no caos.', 'DEZESSEIS_ANOS', 9840000000000, 'FICCAO_CIENTIFICA', 'EM_CARTAZ');
insert into Movies (id, Name, Sinopse, Rating, Duration, Gender, Status)values(70, 'Mad Max: Estrada da Fúria', 'Em um futuro pós-apocalíptico, uma mulher se rebela contra um líder tirano em busca de sua terra natal, e em sua jornada, ela encontra um nômade chamado Max.', 'DEZESSEIS_ANOS', 7200000000000, 'ACAO', 'EM_CARTAZ');
insert into Movies (id, Name, Sinopse, Rating, Duration, Gender, Status)values(80, 'Minha Mãe é uma Peça 3', 'Dona Hermínia precisa se reinventar e lidar com os novos desafios de ser avó, sogra e mãe de filhos adultos.', 'DOZE_ANOS', 6660000000000, 'COMEDIA', 'EM_BREVE');
insert into Movies (id, Name, Sinopse, Rating, Duration, Gender, Status)values(90, 'Parasita', 'A família de Ki-taek está desempregada e vive em um porão. Uma obra do acaso faz com que o filho comece a dar aulas de inglês para uma garota de uma família rica, dando início a uma complexa relação de dependência mútua.', 'DEZESSEIS_ANOS', 7920000000000, 'DRAMA', 'EM_CARTAZ');
insert into Movies (id, Name, Sinopse, Rating, Duration, Gender, Status)values(10, 'A Chegada', 'Uma linguista é recrutada pelo exército para se comunicar com alienígenas que chegaram à Terra. Ela precisa decifrar a linguagem deles para evitar uma guerra global.', 'DOZE_ANOS', 6960000000000, 'FICCAO_CIENTIFICA', 'EM_CARTAZ');
insert into Movies (id, Name, Sinopse, Rating, Duration, Gender, Status)values(11, 'O Resgate do Soldado Ryan', 'Durante a Segunda Guerra Mundial, um grupo de soldados americanos é enviado em uma missão perigosa para resgatar um paraquedista cujos três irmãos foram mortos em combate.', 'DEZOITO_ANOS', 10440000000000, 'ACAO', 'FORA_DE_CARTAZ');