services:
  # Serviço do PostgreSQL
  database:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Samella4551%10
      POSTGRES_DB: MovieTheater
    ports:
      - "5432:5432"
    volumes:
      # Volume para persistir os dados do banco
      - postgres_data:/var/lib/postgresql/data
      # Volume para carregar o script de inicialização do admin (se existir)
      - ./init-db:/docker-entrypoint-initdb.d

  # Serviço da sua aplicação
  app:
    build: .
    container_name: movie_theather_api_app
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/MovieTheater
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Samella4551%10
    restart: always

volumes:
  postgres_data: